server.port: 8080  
spring.profiles.active: dev 
spring.application.name: crawler 
spring.batch.initializer.enabled: false
spring.batch.job.enabled: false
spring.batch.initialize-schema: always

--- 
spring.config.activate.on-profile: dev

#spring.datasource.driver-class-name: org.hsqldb.jdbc.JDBCDriver
#spring.datasource.url: jdbc:hsqldb:mem:crawler;DB_CLOSE_DELAY=-1
#spring.datasource.username: sa
#spring.datasource.password: sa
#spring.jpa.hibernate.ddl-auto: create-drop 

spring.datasource.url: jdbc:mariadb://localhost:3306/crawler?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username: crawler
spring.datasource.password: crawler  
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver  
spring.jpa.hibernate.ddl-auto: none 


spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true 
       
logging.level.org.springframework.data: DEBUG
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
logging.level.com.souljam.crawler: INFO
 
#springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

elasticsearch.host: 127.0.0.1
elasticsearch.port: 9300
elasticsearch.cluster_name: docker-cluster
spring.main.allow-bean-definition-overriding: true
--- 
spring.config.activate.on-profile: prd

spring.datasource.url: jdbc:mariadb://database:3306/crawler?characterEncoding=UTF-8&amp;serverTimezone=UTC
spring.datasource.username: crawler
spring.datasource.password: crawler
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false 
       
logging.level.org.springframework.data: ERROR
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: ERROR
logging.level.org.springframework.jdbc.core.JdbcTemplate: ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: ERROR
logging.level.com.rock.jpetstore: ERROR

springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

schedluer.job.cron: 0 */1 * * * ?

elasticsearch.host: elasticsearch
elasticsearch.port: 9300
elasticsearch.cluster_name: docker-cluster
spring.main.allow-bean-definition-overriding: true