--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N1&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N3&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N4&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N5&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N6&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N7&view_type=sm');
--insert into sites values(UUID(),'autodaily','https://www.autodaily.co.kr/news/articleList.html?sc_section_code=S1N2&view_type=sm');
--insert into sites values(UUID(),'intelligenttransport','https://www.intelligenttransport.com/transport-news/');
--insert into sites values(UUID(),'intelligenttransport','https://www.intelligenttransport.com/transport-articles/');
--insert into sites values(UUID(),'medium','https://medium.com/nextmobility');
--insert into sites values(UUID(),'medium','https://medium.com/mobility-insights');
--insert into sites values(UUID(),'joins','http://jmagazine.joins.com/economist/list/021301');
--insert into sites values(UUID(),'newatlas','https://newatlas.com/transport/');

